# Site settings
title: login.gov
image: /assets/img/login-gov-288x288.png
canonical_domain: www.login.gov

# i18n
languages:
  - en
  - es
  - fr

exclude_from_localizations: ["javascript", "images", "css"]

# Pages
collections:
  pages:
    output: true
    permalink: /:path/

# Scripts
scripts:
  - /assets/js/build/bundle.js

# Styles
styles:
  - /assets/stylesheets/main.css

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
- scope:
    path: "_help"
  values:
    layout: help
- scope:
    path: ""
  values:
    layout: main

include:
  # dotfiles are excluded by default
  - .well-known

exclude:
  - /assets/stylesheets/main.scss
  - Gemfile*
  - Makefile*
  - node_modules
  - package.json
  - scripts
  - spec
  - webpack.config.js
  - vendor

keep_files:
  - /assets/js/build/*
  - /assets/stylesheets/build/*

plugins:
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap

baseurl:

url: https://www.login.gov
