# Site settings
title: login.gov
canonical_domain: www.login.gov

# i18n
languages: ['en', 'es']
exclude_from_localizations: ["javascript", "images", "css"]

# Pages
collections:
  help:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:path/

# Scripts
scripts:
  - /assets/js/build/bundle.js

# Styles
styles:
  - /assets/stylesheets/build/main.css

sass:
  style: compressed

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
- scope:
    path: "_help"
  values:
    layout: help
- scope:
    path: ""
  values:
    layout: main

exclude:
  - /assets/stylesheets/main.scss
  - Gemfile*
  - Makefile*
  - node_modules
  - package.json
  - spec
  - webpack.config.js
  - vendor

gems:
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin

help_pages:
- Creating an account
- Signing in
- Changing settings
- Privacy and security

# Per-section configs
playbook:
  principles:
   - anchor: users
     img: graphic-users
     text: Focus on user needs
   - anchor: transparent
     img: graphic-venn
     text: Be transparent about how it works
   - anchor: flexible
     img: graphic-half-circle
     text: Build a flexible product
   - anchor: privacy
     img: graphic-locks
     text: Use modern privacy practices
   - anchor: security
     img: graphic-hex
     text: Create responsive security systems
