# Site settings
title: login.gov
description: login.gov, the consumer identity platform

# Pages
collections:
  pages:
    output: true
    permalink: /:path/

# Scripts
scripts:
  - /assets/js/build/bundle.js

# Styles
styles:
  - /assets/stylesheets/build/main.css

sass:
  style: compressed

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: main

exclude:
  - /assets/stylesheets/main.scss
  - Gemfile*
  - Makefile*
  - node_modules
  - package.json
  - spec
  - webpack.config.js

# Per-section configs
help_center:
  - anchor: creating-an-account
    text: Creating an account
  - anchor: signing-in
    text: Signing in
  - anchor: changing-settings
    text: Changing settings
  - anchor: privacy-and-security
    text: Privacy and security

playbook:
  principles:
   - anchor: users
     img: graphic-users
     text: Focus on user needs
   - anchor: transparent
     img: graphic-venn
     text: Be transparent about how it works
   - anchor: flexible
     img: graphic-half-circle
     text: Build a flexible product
   - anchor: privacy
     img: graphic-locks
     text: Use modern privacy practices
   - anchor: security
     img: graphic-hex
     text: Create responsive security systems
