# Site settings
title: login.gov
image: /assets/img/login-gov-288x288.png
canonical_domain: www.login.gov

# i18n
languages:
  - en
  - es
  - fr

exclude_from_localizations: ['javascript', 'images', 'css', 'admin/index.html']

# Pages
collections:
  help:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true

# Scripts
scripts:
  - /assets/js/build/main.js

# Styles
styles:
  - /assets/css/main.css

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

autoprefixer:
  browsers:
    - last 2 versions
    - ie 11

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
  - scope:
      path: ''
    values:
      layout: main
  # - scope:
  #     type: 'pages'
  #     path: 'en'
  #   values:
  #     permalink: /:path

include:
  # dotfiles are excluded by default
  - .well-known

exclude:
  - Gemfile*
  - Makefile*
  - node_modules
  - package.json
  - scripts
  - spec
  - webpack.config.js
  - vendor

keep_files:
  - /assets/js/build/*

plugins:
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap
  - jekyll-autoprefixer

help_pages:
  - get-started
  - trouble-signing-in
  - manage-your-account
  - specific-agencies
  - verify-your-identity

baseurl:

url: https://www.login.gov
