# Site settings
title: login.gov
description: login.gov, the consumer identity platform

# Pages
collections:
  pages:
    output: true
    permalink: /:path/

# Styles
styles:
  - /assets/stylesheets/main.css

sass:
    style: compressed

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: main

# Per-section configs
playbook:
  principles:
   - anchor: users
     img: graphic-users
     text: Focus on user needs
   - anchor: transparent
     img: graphic-venn
     text: Be transparent about how it works
   - anchor: flexible
     img: graphic-half-circle
     text: Build a flexible product
   - anchor: privacy
     img: graphic-locks
     text: Use modern privacy practices
   - anchor: security
     img: graphic-hex
     text: Create responsive security systems
