version: 2.1

orbs:
  slack: circleci/slack@3.4.2
commands:
  install-dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: |
            sudo npm install -g n && sudo n 12
            npm ci
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
  build-site:
    steps:
      - run:
          name: build the site
          command: |
            npm run build-js
            bundle exec jekyll build

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node-browsers
    steps:
      - checkout
      - install-dependencies
      - build-site
      - run:
          name: run tests
          command: bundle exec rspec spec
      - run:
          name: check old URLs
          command: bundle exec ./scripts/sitemap-check --directory _site --old-urls-file OLD_URLS.yml
      - run:
          name: Run htmlproofer (no external links)
          command: make htmlproofer_internal

  accessibility:
    docker:
      - image: circleci/ruby:2.6-node-browsers
    steps:
      - checkout
      - install-dependencies
      # It's not necessary to build the site prior to running end-to-end tests, as it's done as a
      # pre-step of the npm test script.
      - run:
          name: run end-to-end tests
          command: npm test

  eslint:
    docker:
      - image: circleci/ruby:2.6-node-browsers
    steps:
      - checkout
      - install-dependencies
      - run:
          name: run ESLint
          command: make lint-js

  check-optimized-assets:
    docker:
      - image: circleci/ruby:2.6-node-browsers
    steps:
      - checkout
      - install-dependencies
      - run:
          name: check optimized images
          command: make lint-assets

  # Running external links as a separate job so we don't fail the build directly
  # but do get the feedback/info
  test-external-links:
    docker:
      - image: circleci/ruby:2.6-node-browsers
    steps:
      - checkout
      - install-dependencies
      - build-site
      - run:
          name: Run htmlproofer (external links only)
          command: make htmlproofer_external
      - slack/status:
          fail_only: true
          failure_message: ":login-gov::red_circle: external link check failed"
          only_for_branches: 'master' # don't notify Slack on a branch build

workflows:
  version: 2
  release:
    jobs:
      - build
      - eslint
      - check-optimized-assets
      - test-external-links
      - accessibility
  daily-external-link-checker:
    jobs:
      - test-external-links
    triggers:
      - schedule:
          # Once a day at 12pm
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
