version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: |
            sudo npm install -g n && sudo n 12
            yarn install
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: build the site
          command: |
            npm run build-css
            npm run build-js
            bundle exec jekyll build
      - run:
          name: run tests
          command: bundle exec rspec spec
      - run:
          name: check old URLs
          command: make test-urls
