title: settings
global:
  title: login.gov
  description: consectetur adipiscing elit.
  skip_nav: Passer au contenu principal
banner:
  official: Un site officiel du gouvernement américain
  how: Voici comment vous savez
  gov_description: >-
    **Les sites Web officiels utilisent .gov**

    Un site Web **.gov** appartient à une organisation gouvernementale officielle des États-Unis.
  secure_description: >-
    **Les sites Web sécurisés .gov utilisent HTTPS**

    Un **verrou** ou **https://** signifie que vous êtes connecté en toute sécurité au site Web .gov. Partagez des informations sensibles uniquement sur des sites Web officiels et sécurisés.
