accessible_labels:
  secondary_navigation: Navigation secondaire
actions:
  search: Chercher
banner:
  one-account-for-govt:
    create: Créer un compte
    learn: Apprendre à créer un compte
    tagline: Votre seul compte pour le gouvernement
  text:
    official: Un site officiel du gouvernement américain
    how: Voici comment vous savez
    gov_heading: Les sites Web officiels utilisent .gov
    gov_description: Un site Web .gov appartient à une organisation gouvernementale officielle des États-Unis.
    secure_heading: Les sites Web sécurisés .gov utilisent HTTPS
    secure_description: 'Un <strong>verrou</strong> ou <strong>https://</strong> signifie que vous êtes connecté en toute sécurité au site Web .gov. Partagez des informations sensibles uniquement sur des sites Web officiels et sécurisés.'
contact_page:
  support_request_form:
    agencies:
      cbp_jobs: Customs and Border Protection Jobs
      cbp_roam: Customs and Border Protection ROAM
      dot_fmcsa: DOT FMCSA (Motor Carrier Safety)
      dot_nrcme: DOT National Registry of Certified Medical Examiners
      ds_logon: DS Logon
      move_mil: DOD Move.mil (Homes or Office)
      other: Other
      railroad_retirement_board: Railroad Retirement Board
      sam: GSA SAM.gov
      sba_dlap: SBA DLAP
      ssa: Social Security Administration (SSA)
      trusted_traveler_program: Trusted Traveler Programs (Global Entry/Nexus/Sentri)
      usajobs: USAJOBS
      veterans_affairs: Veterans Affairs
    errors:
      captcha_required: Vous devez relever le défi de la prévention du pourriel.
    form_helpers:
      select_topic: '- Sélectionnez un sujet -'
      select_issue: '- Sélectionnez une question spécifique -'
      select_agency: '- Sélectionnez une agence -'
    labels:
      agency_application: Demande à une agence
      agency_application_all: Toutes les applications
      agency_application_common: Applications courantes
      agency_application_other: Autres applications
      description: Donnez plus de détails sur votre question
      email: E-mail
      first_name: Prénom
      last_name: Nom
      pii_warning: Veuillez **ne pas** inclure d'informations sensibles ou d'identification dans cette section telles que votre nom complet, votre date de naissance ou votre numéro de sécurité sociale.
      subtopic: Problème
      topic: Sujet
      optional: optionnel
    reset: Formulaire clair
    submit: Soumettre
    subtopics:
      add_family_member: Comment ajouter un membre de la famille à mon compte login.gov?
      agency_app: Problème avec l'appli de l'agence
      authentication_app: Appli d'authentification
      authentication_app_setup: Configuration de l'appli d'authentification
      change_email: Modifier l'adresse e-mail
      change_password: Modifier le mot de passe
      change_phone_number: Modifier le numéro de téléphone
      delete_account: Supprimer le compte
      device_notification: J'ai reçu une alerte concernant une nouvelle connexion sur mon compte login.gov
      email_delivery_issue: Problème de distribution des e-mails
      forgot_password: Mot de passe oublié
      international_number: Numéro international
      invalid_email: E-mail invalide
      invalid_otp: OTP invalide
      locked_out: Verrouillé
      lost_2fa_method: Authentification à deux facteurs perdue
      multiple_otps: Multiples OTP
      new_account: Nouveau compte
      new_personal_key: Nouvelle clé personnelle
      no_otp_received: Aucun OTP reçu
      no_phone: Aucun numéro de téléphone
      none: '--Aucun--'
      other: Autre
      password_issue: Problème de mot de passe
      personal_key: Clé personnelle
      personal_key_setup: Configuration de la clé personnelle
      personal_key_notification: J'ai reçu une alerte concernant l'utilisation de ma clé personnelle pour me connecter
      piv_cac: Je n'arrive pas à utiliser mon PIV / CAC pour me connecter
      privacy_and_security: Confidentialité et sécurité
      recover_account: Comment puis-je me connecter à mon compte si je n'ai pas mon téléphone ou ma clé personnelle?
      remember_device_issue: Problème pour se souvenir de l'appareil
      security_code: Je ne reçois pas le code de sécurité
      security_key: Je ne parviens pas à utiliser ma clé de sécurité pour me connecter
      service_quality: Qualité du service
      site_navigation: Navigation du site
      unwanted_otp: Multiples OTP
      wrong_account_update: Mise à jour de compte erronée
    topics:
      account_linking: Lien vers le compte
      changing_settings: Modifier les paramètres
      creating_account: Créer des comptes
      login_system: Système Login.gov
      mfa: MFA (authentification multi-facteurs)
      not_login_gov: Pas login.gov
      other: Autre
      piv_cac: Problème de PIV/CAC
      signing_in: Connexion
feedback_form:
  'yes': "Oui"
  'no': "Non"
  question: Cet article vous a-t-il été utile?
footer:
  gsa: Administration des services généraux des États-Unis
global:
  language: Langue
  locales:
    en: English
    es: Español
    fr: Français
help_page:
  p_1: Parcourir les sujets communs
  title: Comment pouvons nous aider?
  categories:
    - title: Commencez avec login.gov
      description: Créez votre compte. Découvrez les options d'authentification et d'autres caractéristiques du compte.
      url: /fr/help/get-started/overview/
      image: /assets/img/help/get-started.svg
    - title: Des problèmes pour vous connecter?
      description: Vous avez oublié votre mot de passe ? Votre compte est bloqué ? Nous vous aiderons à résoudre vos problèmes d'accès.
      url: /fr/help/trouble-signing-in/overview/
      image: /assets/img/help/trouble-signing-in.svg
    - title: Gérez votre compte
      description: Modifiez les paramètres de votre compte, notamment votre mot de passe, votre numéro de téléphone, votre adresse électronique, etc.
      url: /fr/help/manage-your-account/overview/
      image: /assets/img/help/manage-your-account.svg
    - title: Assistance auprès des agences spécifiques
      description: Obtenez de l'aide avec Trusted Traveler Programs (TTP), SAM.gov.
      url: /fr/help/specific-agencies/overview/
      image: /assets/img/help/help-specific-agencies.svg
    - title: Vérifiez votre identité
      description: Découvrez les différentes options de vérification de votre identité.
      url: /fr/help/verify-your-identity/overview/
      image: /assets/img/help/verify-your-id.svg
help_subpages:
  get-started: Commencez avec login.gov
  trouble-signing-in: Des problèmes pour vous connecter?
  manage-your-account: Gérez votre compte
  specific-agencies: Aide aux agences spécifiques
  verify-your-identity: Vérifiez votre identité
meta:
  about:
    description: Plus d'informations sur login.gov
    title: Plus d'informations
  contact:
    title: Contact
  contact_us:
    description: Vous avez une question ou un problème concernant login.gov?
    title: Nous joindre
  developers:
    title: Développeurs
  help:
    description: Trouvez des réponses aux questions fréquentes concernant login.gov.
    title: Aide
  home:
    description: Utilisez un seul compte pour un accès sécurisé et privé aux prestations et services fédéraux.
    title: Accueil
  implementation:
    description: Déterminez si votre agence ou votre organisme a besoin d'un système
      de gestion de l'identité des utilisateurs.
    title: Mise en œuvre
  not_found:
    title: '404'
  playbook:
    description: Aider les développeurs et les technologues des agences gouvernementales
      à mettre en place des systèmes de gestion de l'identité des utilisateurs pratiques,
      sécuritaires et respectueux de la vie privée.
    title: Guide de mise en œuvre relatif à l'identité
  principles:
    description: Explorez les principes qui nous ont permis de concevoir le meilleur
      système possible.
    title: Principes
  privacy_and_security:
    description: Découvrez nos pratiques de sécurité et de confidentialité.
    title: Confidentialité et sécurité
  privacy_policy:
    title: Politique de confidentialité
  what-is-login:
    description: Un résumé de ce qu'est login.gov et du service qu'il fournit.
    title: Qu'est-ce que login.gov?
  who-uses-login:
    description: Une liste de clients bénéficiant actuellement des services login.gov
    title: Qui utilise login.gov?
  why-login-gov:
    description: Les agences gouvernementales américaines peuvent tirer parti de la plate-forme d'authentification et de vérification d'identité de login.gov. En savoir plus sur les offres et les opportunités de login.gov.
    title: Pourquoi login.gov
nav:
  accessibility:
    title: Accessibilité
    sections:
      - name: Notre engagement
        url: '#notre-engagement'
      - name: Normes
        url: '#normes'
      - name: Évaluation
        url: '#évaluation'
      - name: Limites connues
        url: '#limites-connues'
  about_us: À propos de nous
  anchor_to_top: Retour au sommet
  become_a_partner: Devenir un partenaire
  contact_us:
    title: Nous contacter
    sections:
      - name: Avez-vous une question concernant votre compte d’agence?
        url: '#avez-vous-une-question-concernant-votre-compte-dagence'
      - name: Partenaire avec login.gov
        url: '#partenaire-avec-logingov'
      - name: Signaler un problème
        url: '#signaler-un-problème'
  contact_login_gov: Contactez Login.gov
  create_an_account: Créer un compte
  developer_guide: Guide du développeur
  developers: Développeurs
  groups:
    agencies: Pour les agences
    learn: Apprendre
    support: Soutien
  help: Aide
  help_center: Centre d'aide
  home: Accueil
  implementation: Mise en œuvre
  menu: Menu
  overview: Aperçu
  playbook: Guide de mise en œuvre
  policies:
    title: Confidentialité et sécurité
    sections:
      - name: Notre engagement envers votre confidentialité et votre sécurité
        url: /fr/policy/
      - name: Comment ça marche?
        url: /fr/policy/how-does-it-work/
      - name: Notre déclaration de confidentialité
        url: /fr/policy/our-privacy-act-statement/
      - name: Nos pratiques de sécurité
        url: /fr/policy/our-security-practices/
      - name: Termes et conditions de la messagerie
        url: /fr/policy/messaging-terms-and-conditions/
      - name: Règles d'utilisation
        url: /fr/policy/rules-of-use/
  principles: Principes
  privacy_&_security: Confidentialité et sécurité
  security: Sécurité
  sign_in: 'Connectez-vous avec'
  skip_nav: Passer au contenu principal
  system_status: État du système login.gov
  what_is_login_gov: Qu'est-ce que login.gov?
  who_uses_login_gov: Qui utilise login.gov?
who-uses-login-page:
  hero:
    heading: Qui utilise login.gov?
    text: Login.gov est un service de connexion approuvé par le gouvernement. Le public utilise login.gov pour un accès simple et sécurisé aux services fournis par nos partenaires gouvernementaux.
  partners: |-
    ## Nos partenaires

    Nos partenaires gouvernementaux participants offrent une variété de services tels que:

    * USAJOBS (Bureau de la gestion du personnel)
    * Programme de protection des chèques de paie (Small Business Administration)
    * Programme de demandes de prêts en cas de catastrophe (Small Business Administration)

    <div class="mobile partners-img" aria-hidden="true"></div>
  security: |-
    Login.gov adhère aux dernières [normes de sécurité](__LOCALE_BASE_URL__/security) établies par des organisations de sécurité de premier plan telles que le [National Institute of Standards and Technology](https://www.nist.gov/), le [Cybersecurity National Action Plan](https://www.hsdl.org/c/cybersecurity-national-action-plan/) et le [Service fédéral des acquisitions](https://www.gsa.gov/about-us/organization/federal-acquisition-service)

    Les agences choisissent login.gov parce que nous fournissons une solution simple et sécurisée. [En savoir plus sur notre programme de partenariat](https://partners.login.gov).
create-an-account:
  hero:
    heading: Créer un compte
    text: Rejoignez les millions de personnes qui font confiance à login.gov pour un accès sûr et sécurisé aux agences gouvernementales.
  intro: Lorsque vous serez prêt à créer votre compte login.gov sécurisé, vous devrez fournir quelques informations&#58;
  step_1: |-
    ## 1. Adresse électronique
      * Nous vous recommandons une adresse e-mail personnelle à laquelle vous pourrez toujours accéder plutôt qu'une adresse e-mail professionnelle.
      * Si vous possédez déjà un compte avec login.gov avec cette adresse e-mail, nous vous enverrons un e-mail pour vous indiquer comment réinitialiser votre mot de passe et accéder au compte.
  step_2: |-
    ## 2. Mot de passe sécurisé
      * Les mots de passe doivent comporter au moins 12 caractères et ne doivent pas inclure de mots ou d'expressions couramment utilisés.
  step_3: |-
    ## 3. Une ou plusieurs [méthodes d'authentification](__LOCALE_BASE_URL__/help/authentication-methods/which-authentication-method-should-i-use/) telles que&#58;
      * __Plus sécurisé__
        * Clef de sécurité
        * Application d'authentification
        * Employé du gouvernement fédéral ou identification militaire (PIV/CAC)
      * __Moins sécurisé__
        * SMS/messages texte
        * Codes de sauvegarde
  info: Selon les besoins de sécurité de l'agence, vous devrez peut-être prouver votre identité à l'aide d'un numéro de sécurité sociale, d'une adresse et / ou d'une pièce d'identité émise par l'État américain.
identifier:
  accessible_labels:
    description: Agency description # TODO: Translate
    identifier: Agency identifier # TODO: Translate
    links: Important links # TODO: Translate
    logo: GSA logo # TODO: Translate
    usa_gov: U.S. government information and services # TODO: Translate
  disclaimer: An official website of the [General Services Administration](https://gsa.gov) # TODO: Translate
  links:
    about_agency: About GSA # TODO: Translate
    accessibility: Accessibility support # TODO: Translate
    foia: FOIA requests # TODO: Translate
    ig: Office of the Inspector General # TODO: Translate
    no_fear_act: No FEAR Act data # TODO: Translate
    performance: Performance reports # TODO: Translate
    privacy: Privacy policy # TODO: Translate
  usa_gov:
    text: Looking for U.S. government information and services? # TODO: Translate
    link: Visit USA.gov # TODO: Translate
