title: settings
global:
  title: login.gov
  description: Nulla porttitor accumsan tincidunt.
  skip_nav: Salte al contenido principal
banner:
  official: Un sitio web oficial del gobierno de los Estados Unidos
  how: Así es como sabes
  gov_description: >-
    **Los sitios web oficiales usan .gov**

    Un sitio web **.gov** pertenece a una organización oficial del Gobierno de Estados Unidos.
  secure_description: >-
    **Los sitios web oficiales usan .gov**

    Un **candado** o **https://** significa que usted se conectó de forma segura a un sitio web .gov. Comparta información sensible sólo en sitios web oficiales y seguros.
