404_page:
  content:
    p_1: 'En su lugar, aquí hay algunos enlaces que pueden ser útiles:'
  heading: Esta página ya no está disponible
  links:
    - title: Inicio
      url: /
    - title: Centro de ayuda
      url: /help/
accessible_labels:
  secondary_navigation: Navegación secundaria
actions:
  search: Buscar
banner:
  one-account-for-govt:
    create: Crea una cuenta
    learn: Aprender a crear una cuenta
    tagline: Su única cuenta para el gobierno
  text:
    official: Un sitio web oficial del gobierno de los Estados Unidos
    how: Así es como sabes
    gov_heading: Los sitios web oficiales usan .gov
    gov_description: Un sitio web .gov pertenece a una organización oficial del Gobierno de Estados Unidos.
    secure_heading: os sitios web seguros .gov usan HTTPS
    secure_description: 'Un <strong>candado</strong> o <strong>https://</strong> significa que usted se conectó de forma segura a un sitio web .gov. Comparta información sensible sólo en sitios web oficiales y seguros.'
contact_page:
  support_request_form:
    agencies:
      cbp_jobs: Customs and Border Protection Jobs
      cbp_roam: Customs and Border Protection ROAM
      dot_fmcsa: DOT FMCSA (Motor Carrier Safety)
      dot_nrcme: DOT National Registry of Certified Medical Examiners
      ds_logon: DS Logon
      move_mil: DOD Move.mil (Homes or Office)
      other: Other
      railroad_retirement_board: Railroad Retirement Board
      sam: GSA SAM.gov
      sba_dlap: SBA DLAP
      ssa: Social Security Administration (SSA)
      trusted_traveler_program: Trusted Traveler Programs (Global Entry/Nexus/Sentri)
      usajobs: USAJOBS
      veterans_affairs: Veterans Affairs
    errors:
      captcha_required: Debes superar el desafío de prevención de spam.
    form_helpers:
      select_topic: '- Seleccione un tema -'
      select_issue: '- Seleccione un problema específico -'
      select_agency: '- Seleccione una solicitud de agencia -'
    labels:
      agency_application: Aplicación de agencia
      agency_application_all: Todas las aplicaciones
      agency_application_common: Aplicaciones comunes
      agency_application_other: Otras aplicaciones
      description: Proporciona más detalles acerca de tu pregunta
      email: Correo electrónico
      first_name: Nombre
      last_name: Apellido
      pii_warning: '**No** incluya información sensible o de identificación en esta sección, como su nombre completo, fecha de nacimiento o número de seguro social.'
      subtopic: Problema
      topic: Tema
      optional: opcional
    reset: Limpiar formulario
    submit: Enviar
    subtopics:
      add_family_member: ¿Cómo agrego un familiar a mi cuenta login.gov?
      agency_app: Problema con la aplicación de la agencia
      authentication_app: Aplicación de autenticación
      authentication_app_setup: Instalación de la aplicación de autenticación
      change_email: Cambiar correo electrónico
      change_password: Cambiar contraseña
      change_phone_number: Cambiar número de teléfono
      delete_account: Eliminar cuenta
      device_notification: Recibí una alerta sobre un nuevo inicio de sesión en mi cuenta login.gov
      email_delivery_issue: Problema con el envío de correos electrónicos
      forgot_password: Olvidé la contraseña
      international_number: Número internacional
      invalid_email: Número no válido
      invalid_otp: Pedido de pago no válido
      locked_out: Bloqueado
      lost_2fa_method: Método autenticación de dos factores perdido
      multiple_otps: Múltiples pedidos de pago
      new_account: Nueva cuenta
      new_personal_key: Nueva clave personal
      no_otp_received: No se ha recibido ningún pedido de pago
      no_phone: No hay teléfono
      none: '--Ninguno--'
      other: Otro
      password_issue: Problema con la contraseña
      personal_key: Clave personal
      personal_key_setup: Configuración de la clave personal
      personal_key_notification: Recibí una alerta sobre el uso de mi clave personal para iniciar sesión
      piv_cac: Tengo problemas para usar mi PIV / CAC para iniciar sesión
      privacy_and_security: Privacidad y seguridad
      recover_account: ¿Cómo inicio sesión en mi cuenta si no tengo mi teléfono o mi clave personal?
      remember_device_issue: Recordar problema con el dispositivo
      security_code: No recibo el código de seguridad
      security_key: Tengo problemas para usar mi clave de seguridad para iniciar sesión
      service_quality: Calidad del servicio
      site_navigation: Navegación en la página web
      unwanted_otp: Múltiples pedidos de pago
      wrong_account_update: Actualización de la cuenta errónea
    topics:
      account_linking: Vinculación de cuenta
      changing_settings: Cambiando ajustes
      creating_account: Creando cuentas
      login_system: Sistema login.gov
      mfa: MFA (autenticación multifactor)
      not_login_gov: No es login.gov
      other: Otro
      piv_cac: Problema con CAC (tarjeta de acceso común) o PIV (verificación de identidad
        personal)
      signing_in: Iniciando sesión
footer:
  gsa: Administración General de Servicios de EE. UU.
global:
  language: Idioma
  locales:
    en: English
    es: Español
    fr: Français
help_page:
  p_1: Explore los temas comunes
  title: ¿Cómo podemos ayudar?
  categories:
    - title: Empiece con login.gov
      description: Cree su cuenta. Conozca las opciones de autenticación y más características de la cuenta.
      url: /es/help/get-started/overview/
      image: /assets/img/help/get-started.svg
    - title: ¿Tiene problemas para iniciar sesión?
      description: ¿Olvidó su contraseña? ¿Se bloqueó su cuenta? Le ayudaremos a solucionar los problemas de acceso.
      url: /es/help/trouble-signing-in/overview/
      image: /assets/img/help/trouble-signing-in.svg
    - title: Administrar su cuenta
      description: Cambia la configuración de la cuenta, incluida la contraseña, el teléfono, el correo electrónico y más.
      url: /es/help/manage-your-account/overview/
      image: /assets/img/help/manage-your-account.svg
    - title: Asistencia de agencias específicas
      description: Obtenga ayuda con Trusted Traveler Programs (TTP), SAM.gov.
      url: /es/help/specific-agencies/overview/
      image: /assets/img/help/help-specific-agencies.svg
    - title: Verifique su identidad
      description: Aprenda sobre las opciones para verificar su identidad.
      url: /es/help/verify-your-identity/overview/
      image: /assets/img/help/verify-your-id.svg
help_subpages:
  get-started: Empiece con login.gov
  trouble-signing-in: ¿Tiene problemas para iniciar sesión?
  manage-your-account: Administrar su cuenta
  specific-agencies: Ayuda con agencias específicas
  verify-your-identity: Verificación de identidad
meta:
  contact:
    title: Contacto
  contact_us:
    description: '¿Tiene alguna pregunta o problema con login.gov?'
    title: Contáctenos
  developers:
    title: Desarrolladores
  help:
    description: Obtenga respuestas a preguntas comunes sobre login.gov.
    title: Ayuda
  home:
    description: Use una cuenta para tener acceso privado y seguro a los beneficios y servicios federales.
    title: Inicio
  implementation:
    description: Determine si su agencia u organización necesita un sistema de gestión
      de la identidad del consumidor.
    title: Implementación
  not_found:
    title: '404'
  playbook:
    description: Ayudar a los desarrolladores y tecnólogos de los organismos gubernamentales
      a crear sistemas de administración de la identidad de los consumidores que sean
      útiles, seguros y que garanticen la protección de la privacidad.
    title: Manual de identidad
  principles:
    description: Explore los principios que nos han ayudado a hacer el mejor sistema
      posible.
    title: Principios
  privacy_and_security:
    description: Obtenga más información sobre nuestras prácticas de seguridad y privacidad.
    title: Privacidad y seguridad
  privacy_policy:
    title: Política de privacidad
  what-is-login:
    description: Un resumen de lo que es login.gov y el servicio que brinda.
    title: ¿Qué es login.gov
  who-uses-login:
    description: Una lista de clientes que se benefician actualmente de los servicios de login.gov
    title: ¿Quién usa login.gov?
  why-login-gov:
    description: Las agencias gubernamentales de EE. UU. Pueden aprovechar la plataforma de autenticación y verificación de identidad de login.gov. Obtenga más información sobre las ofertas y oportunidades de login.gov.
    title: Por qué login.gov
nav:
  accessibility:
    title: Accesibilidad
    sections:
      - name: Nuestro compromiso
        url: '#nuestro-compromiso'
      - name: Estándares
        url: '#estándares'
      - name: Evaluación
        url: '#evaluación'
      - name: Limitaciones conocidas
        url: '#políticas-de-accesibilidad'
  about_us: Sobre nosotros
  anchor_to_top: Volver arriba
  become_a_partner: Convertirse en un compañero
  contact_us:
    title: Contacta con nosotros
    sections:
      - name: ¿Tiene alguna pregunta sobre la cuenta de su agencia?
        url: '#tiene-alguna-pregunta-sobre-la-cuenta-de-su-agencia'
      - name: Asociarse con login.gov
        url: '#asociarse-con-logingov'
      - name: Reportar un problema
        url: '#reportar-un-problema'
  contact_login_gov: Póngase en contacto con Login.gov
  create_an_account: Crea una cuenta
  developer_guide: Guía para desarrolladores
  developers: Desarrolladores
  groups:
    agencies: Para agencias
    learn: Aprender
    support: Apoyo
  help: Ayuda
  help_center: Centro de ayuda
  home: Inicio
  implementation: Implementación
  menu: Menú
  overview: Resumen
  playbook: Manual
  policies:
    title: Privacidad y seguridad
    sections:
      - name: Nuestro compromiso con su privacidad y seguridad
        url: /es/policy/
      - name: ¿Cómo funciona?
        url: /es/policy/how-does-it-work/
      - name: Nuestra declaración de la ley de privacidad
        url: /es/policy/our-privacy-act-statement/
      - name: Nuestras prácticas de seguridad
        url: /es/policy/our-security-practices/
      - name: Términos y condiciones de mensajería
        url: /es/policy/messaging-terms-and-conditions/
  principles: Principios
  privacy_&_security: Privacidad y seguridad
  security: Seguridad
  sign_in: 'Inicie sesión con'
  skip_nav: Salte al contenido principal
  system_status: Estado del sistema login.gov
  what_is_login_gov: ¿Qué es login.gov?
  who_uses_login_gov: ¿Quién usa login.gov?
policies:
  title: Privacidad y seguridad
  sections:
    - name: Nuestro compromiso con su privacidad y seguridad
      url: '/policy/'
      sublinks:
        - text: Cómo trabajamos con nuestras agencias asociadas
          url: '#how-we-work-with-our-partner-agencies'
    - name: ¿Cómo funciona?
      url: '/policy/how-does-it-work/'
    - name: Nuestra declaración de la ley de privacidad
      url: '/policy/our-privacy-act-statement/'
      sublinks:
        - text: La Autoridad - ¿Quién autoriza la recopilación de estos datos?
          url: '#authority'
        - text: El propósito - ¿Por qué necesitamos su información?
          url: '#purpose'
        - text: Usos de rutina - ¿Con quién se comparte habitualmente la información?
          url: '#routine-uses'
        - text: Consentimiento - ¿Cómo puede controlar qué información se comparte?
          url: '#consent'
        - text: Registros - ¿Dónde puede encontrar más información?
          url: '#records'
        - text: Análisis de sitios web
          url: '#analytics'
        - text: Evaluación del impacto en la privacidad
          url: '#impact'
    - name: Nuestras prácticas de seguridad
      url: '/policy/our-security-practices/'
      sublinks:
        - text: Política de divulgación de vulnerabilidades
          url: '#vdp'
        - text: Para más información
          url: '#more-info'
    - name: Términos y condiciones de mensajería
      url: '/policy/messaging-terms-and-conditions/'
      sublinks:
        - text: Términos y condiciones de SMS
          url: '#terms'
who-uses-login-page:
  hero:
    heading: ¿Quién usa login.gov?
    text: Login.gov es un servicio de inicio de sesión de confianza emitido por el gobierno. El público usa login.gov para tener acceso simple y seguro a los servicios que brindan nuestros socios gubernamentales.
  partners: |-
    ## Nuestros compañeros

    Nuestros socios gubernamentales participantes ofrecen una variedad de servicios como:

    * USAJOBS (Oficina de Gestión de Personal)
    * Programa de protección de cheques de pago (Administración de pequeñas empresas)
    * Programa de solicitudes de préstamos por desastre (Administración de pequeñas empresas)

    <div class="mobile partners-img" aria-hidden="true"></div>
  security: |-
    Login.gov se adhiere a los últimos [estándares de seguridad](site.baseurl/security) establecidos por las principales organizaciones de seguridad como el [Instituto Nacional de Estándares y Tecnología](https://www.nist.gov/), el [Plan de Acción Nacional de Ciberseguridad](https://www.hsdl.org/c/cybersecurity-national-action-plan/) y el [Servicio federal de adquisiciones](https://www.gsa.gov/about-us/organization/federal-acquisition-service)

    Las agencias eligen login.gov porque ofrecemos una solución segura y sencilla. [Lea más sobre nuestro programa de socios](https://partners.login.gov).
create-an-account:
  hero:
    heading: Crea una cuenta
    text: Únase a los millones de personas que confían en login.gov para tener acceso seguro a agencias gubernamentales.
  intro: Cuando esté listo para crear su cuenta segura de login.gov, deberá proporcionar algunos datos&#58;
  step_1: |-
    ## 1. Dirección de correo electrónico
      * Recomendamos una dirección de correo electrónico personal a la que siempre podrá acceder en lugar de una dirección de correo electrónico del trabajo.
      * Si ya tiene una cuenta con login.gov con esa dirección de correo electrónico, le enviaremos un correo electrónico para informarle cómo puede restablecer su contraseña y acceder a la cuenta.
  step_2: |-
    ## 2. Contraseña segura
      * Las contraseñas deben tener al menos 12 caracteres y no deben incluir palabras o frases de uso común.
  step_3: |-
    ## 3. Uno o más [métodos de autenticación](site.baseurl/help/authentication-methods/which-authentication-method-should-i-use/) como&#58;
      * __Mas segura__
        * Clave de seguridad
        * Aplicación de autenticación
        * Identificación militar o de empleado del gobierno federal (PIV / CAC)
      * __Menos segura__
        * SMS / mensajes de texto
        * Códigos de respaldo
  info: Dependiendo de las necesidades de seguridad de la agencia, es posible que deba probar su identidad mediante un número de seguro social, una dirección y / o una identificación emitida por Los Estados Unidos.
identifier:
  accessible_labels:
    description: Descripción de la agencia
    identifier: Identificador de la agencia
    links: Enlaces importantes
    logo: Logo de la GSA
    usa_gov: Información y servicios del Gobierno de EE. UU.
  disclaimer: Un sitio web oficial de [General Services Administration](https://gsa.gov)
  links:
    about_agency: Acerca de GSA
    accessibility: Soporte de accesibilidad
    foia: Solicitud a través de FOIA
    ig: Oficina del Inspector General
    no_fear_act: Datos de la ley No FEAR
    performance: Informes de desempeño
    privacy: Política de privacidad
  usa_gov:
    text: ¿Necesita información y servicios del Gobierno?
    link: Visite USAGov en Español
