# Netlify CMS Settings
## Comment out when doing local development
# backend:
#   name: github
#   repo: 18f/identity-site
#   branch: ca-LG-4064-netlifycms
#   base_url: https://federalistapp.18f.gov
#   auth_endpoint: external/auth/github
#   preview_context: federalist/build
#   use_graphql: true

#
# Uncomment when doing local development on Netlify CMS
# Run `npx netlify-cms-proxy-server` to start working locally
# In another terminal, start the app with `make build && make run`
# See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
#

backend:
  name: git-gateway
  branch: ca-LG-4064-netlifycms
  proxy_url: http://localhost:8081/api/v1
local_backend: true

#
#

media_folder: assets/img
public_folder: /images/img
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Help article
    name: help
    folder: _pages/help/
    create: true
    slug: '{{fields.topic}}/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'help' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options:
            [
              { label: 'English', value: 'en' },
              { label: 'Spanish', value: 'sp' },
              { label: 'French', value: 'fr' },
            ],
          default: 'en',
        }
      - {
          label: 'Topic',
          name: 'topic',
          widget: 'select',
          options:
            [
              { label: 'Get started with login.gov', value: 'get-started' },
              { label: 'Manage your account', value: 'trouble-signing-in' },
              { label: 'Verify your identity', value: 'manage-your-account' },
              { label: 'Trouble signing in?', value: 'verify-your-identity' },
              { label: 'Help with specific agencies', value: 'specific-agencies' },
            ],
          default: 'get-started',
        }
      - { label: 'Order', name: 'order', widget: 'number', default: '0' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Redirect from',
          name: 'redirect_from',
          widget: 'list',
          hint: 'Comma-separated list of urls.',
        }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string' }
  - label: Blog post
    name: posts
    folder: _posts/
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
