title: settings
global:
  title: login.gov
  description: Lorem ipsum dolor sit amet.
  skip_nav: Skip to main content
banner:
  gov_description: >-
    **Secure .gov websites use HTTPS**

    A **.gov** website belongs to an official government organization in the United States.
  official: An official website of the United States government
  how: Here’s how you know
  secure_description: >-
    **Os sitios web seguros .gov usan HTTPS**

    A **lock** or **https://** means you’ve safely connected to the .gov website. Share sensitive information only on official, secure websites.
